name: AstraTowny
version: '0.1'
main: dev.loveeev.astratowny.AstraTowny
api-version: '1.20'
softdepend: ["PlaceholderAPI"]
commands:
  towny:
    aliases:
      - t
      - astratowny
      - town
  language:
  nation:
    aliases:
      - n
  townyadmin:
    aliases:
      - ta
      - tadmin
    permission: astratowny.admin

permissions:
  astratowny.admin:
    default: op